name: Weekly Sync from branch '4.3.0' to 'main'

# Schedule to run weekly on Friday at 3:15 PM UTC
on:
  schedule:
    - cron: '20 9 * * 1'  # Adjust this cron expression for your preferred time

jobs:
  sync_pr:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create a pull request using the GitHub CLI
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync branch 4.3.0 with main'
          branch: 4.3.0
          base: main
          title: 'Weekly Sync: branch 4.3.0 to main'
          body: 'Automated weekly sync from branch 4.3.0 to main.'
