name: Weekly Sync from branch '4.3.0' to 'main'

# Schedule to run weekly on Friday at 3:15 PM UTC
on:
  schedule:
    - cron: '50 3 * * 2'  # Adjust this cron expression for your preferred time

jobs:
  sync_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset 4.3.0 branch
        run: |
          git fetch origin propertyM:propertyM
          git reset --hard propertyM
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: propertyM
